name: Migrate

on: ["push"]

jobs:
  migrate:
    name: Migrate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        uses: bahmutov/npm-install@v1.8.28

      - name: Migrate Prisma
        run: npx prisma migrate deploy
